# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58bc56cfda109e8a81d957af5cc513a840663b14e7b0b7fc6fb25603121d8dda2ca4ece3690072de91c06ec93db9634af5ee7e10cef11dfe045b536e1c41a7db

test:
  secret_key_base: 0b2d167d755aa395ef933323831cda23370d826df654738bb001435e35c38f46093155e0547fd33cd68b4963c1fd7f55551f1232ba4e96ae33ed26d962197ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
